// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANLVKQKY1--OFYiCgMgMjzoEStk86c_zQ',
    appId: '1:1087992886722:web:b5ea7d914bf554a445d25b',
    messagingSenderId: '1087992886722',
    projectId: 'lucky-ai-eb8c9',
    authDomain: 'lucky-ai-eb8c9.firebaseapp.com',
    storageBucket: 'lucky-ai-eb8c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzf4yvFthw5HiLyH_QICtB3fpiPj4GxgQ',
    appId: '1:1087992886722:android:8a576771e714a76e45d25b',
    messagingSenderId: '1087992886722',
    projectId: 'lucky-ai-eb8c9',
    storageBucket: 'lucky-ai-eb8c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD46w3uQVWwBLPQRFu8Gd4Wm1TaFa0sTYI',
    appId: '1:1087992886722:ios:5858bb8d8b47833545d25b',
    messagingSenderId: '1087992886722',
    projectId: 'lucky-ai-eb8c9',
    storageBucket: 'lucky-ai-eb8c9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD46w3uQVWwBLPQRFu8Gd4Wm1TaFa0sTYI',
    appId: '1:1087992886722:ios:5858bb8d8b47833545d25b',
    messagingSenderId: '1087992886722',
    projectId: 'lucky-ai-eb8c9',
    storageBucket: 'lucky-ai-eb8c9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANLVKQKY1--OFYiCgMgMjzoEStk86c_zQ',
    appId: '1:1087992886722:web:315f751f5a667e2c45d25b',
    messagingSenderId: '1087992886722',
    projectId: 'lucky-ai-eb8c9',
    authDomain: 'lucky-ai-eb8c9.firebaseapp.com',
    storageBucket: 'lucky-ai-eb8c9.firebasestorage.app',
  );
}
